name = "Star-Field-Client_Lite"
author = "ManyStars"
version = "1.0.0.0-beta.1+26A2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6827f583ccf0b23c96f022c01cf4ef11a5f59c3ec0f65c8296bbc237331ac006"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
